// Generated by CoffeeScript 1.7.1
var QUERY, beeGenerator;

QUERY = 'bees';

beeGenerator = {
  searchOnFlickr_: "https://secure.flickr.com/services/rest/?method=flickr.photos.search&api_key=90485e931f687a9b9c2a66bf58a3861a&text=" + (encodeURIComponent(QUERY)) + "&safe_search=0&content_type=1&sort=interestingness-desc&per_page=20",
  requestBees: function() {
    var req;
    req = new XMLHttpRequest();
    req.open("GET", this.searchOnFlickr_, true);
    req.onload = this.showPhotos_;
    return req.send(null);
  },
  showPhotos_: (function(_this) {
    return function(e) {
      var bee, bees, img, _i, _len;
      bees = e.target.responseXML.querySelectorAll('photo');
      for (_i = 0, _len = bees.length; _i < _len; _i++) {
        bee = bees[_i];
        img = document.createElement('img');
        img.src = _this.constructBeeURL_(bee);
        img.setAttribute('alt', bee.getAttribute('title'));
        document.body.appendChild(img);
      }
    };
  })(this),
  constructBeeURL_: function(photo) {
    return "http://farm" + (photo.getAttribute("farm")) + ".static.flickr.com/" + (photo.getAttribute("server")) + "/" + (photo.getAttribute("id")) + "_" + (photo.getAttribute("secret")) + "_s.jpg";
  }
};

document.addEventListener('DOMContentLoaded', function() {
  return beeGenerator.requestBees;
});
